### ISSUE TITLE
Coverage over 100% for processes

### ISSUE THREAD

**Issue by bulivlad** [camunda-community-hub/camunda-process-test-coverage#338] opened 2023-05-28 11:01 UTC
Having multiple test methods, covering different scenarios on the same process will produce coverage above 100%.
The processes having coverage above 100% are call activities in the main process. 

<img width="1000" alt="image" src="https://github.com/camunda-community-hub/camunda-process-test-coverage/assets/6691306/fa94b592-04b8-46e3-bd5f-c2c4ca59c861">

**Comment by rohwerj** [comment] 2023-06-02 12:56
Was not able to reproduce this issue locally. 
Could you please provide a report.json or report.html with this error?  
That would help a lot in identifying the problem.

**Comment by bulivlad** [comment] 2023-06-05 18:38
hi @rohwerj,

In this [gist](https://gist.github.com/bulivlad/e2da63c4ffeb8fad473baa347384340e) you have the report html and json + the bpmn file and test file I was using to reproduce the behaviour. 
I'm really trying to mock the call activity with dummy process - either start->end process or start->throwing event - to focus on the main process.

Let me know if you need more details on it.

**Comment by bulivlad** [comment] 2023-06-09 07:45
@rohwerj yes, I'm creating dummy processes in real scenario to test the process in isolation without including call activities which are teste separately.
this is the code that creates the dummy process
```
    public static BpmnModelInstance emptyExecutableProcess(String processId) {
        return Bpmn.createExecutableProcess(processId)
                .startEvent()
                .endEvent()
                .done();
    }
```
I tried the solution you suggested and it is working fine.

**Comment by bulivlad** [comment] 2023-06-09 13:02
also strange thing it's happening, I have a total of 24 tests running but the aggregated report json file is around 400MB and reporting around 2000 suites run.

**Comment by rohwerj** [comment] 2023-06-09 19:27
@bulivlad 
Creating a dummy process like you do, will create nodes with auto generated ids. That makes it impossible for the extension to match those to the ones in the model. It anyway makes no sense to include dummy processes in the coverage and it will even mess up the report, as that process model might overwrite the real one in the generated report.

**Comment by rohwerj** [comment] 2023-06-09 19:29
@bulivlad 
For 24 test clauses it's reporting 2000 suites? That really sounds strange and that might be a bug. 
Or are there 2000 runs? Those are all test methods in the classes.
But even for that it sounds a little bit too much. 
Can you somehow share the report files?

**Comment by rohwerj** [comment] 2023-06-20 15:31
@bulivlad Could you open a new ticket with more information regarding the big report.json file? Then we can close this issue, as the coverage over 100% is adressed by excluding the dummy processes from the coverage.

**Comment by bulivlad** [comment] 2023-06-21 09:13
sure @rohwerj, you can close this one. I'm trying to reproduce the big report file in a dummy project. I will open a new issue when I got it.
Thanks

**Closed** 2023-06-21 19:27 UTC
